# Gestion des Tables en PostgreSQL

## Créer une Table
- Syntaxe : 
```sql
CREATE TABLE nom_table (colonne1 type1, colonne2 type2, ...) ;
```

## Alias de table
- Créer une nouvelle table à partir du résultat d'une requête.

```sql
CREATE TABLE nouvelle_table AS SELECT colonnes FROM table_existante WHERE condition ;
```

## Colonne Auto-Incrément avec SERIAL
- Ajouter une colonne avec incrémentation automatique.
```sql
CREATE TABLE nom_table (id SERIAL, ...) ;

```


## Séquences
- Générer une séquence de nombres (pour l'utilise dans d'autres requêtes
- On peut customiser la sequence : [doc officielle](https://www.postgresql.org/docs/current/sql-createsequence.html)
  
```sql
CREATE SEQUENCE nom_sequence ;
```

## Colonne Identité
- Utiliser la colonne identité pour la génération automatique de valeurs.
```sql
CREATE TABLE nom_table (id INT GENERATED BY DEFAULT AS IDENTITY, ...) ;
```

## Modifier une Table (Alter Table)
```sql
ALTER TABLE nom_table ACTION ;
```

### Renommer une Table
```sql
ALTER TABLE ancien_nom RENAME TO nouveau_nom ;
```

### Ajouter une Colonne
```sql
ALTER TABLE nom_table ADD COLUMN nouvelle_colonne type ;
```

### Supprimer une Colonne
```sql
ALTER TABLE nom_table DROP COLUMN nom_colonne ;
```

### Changer le Type de Données d'une Colonne
```sql
ALTER TABLE nom_table ALTER COLUMN colonne TYPE nouveau_type ;
```

### Renommer une Colonne
```sql
ALTER TABLE nom_table RENAME COLUMN ancien_nom TO nouveau_nom ;
```
### Supprimer une Table
```sql
DROP TABLE nom_table ;
```
### Vider une Table (Truncate Table)
```sql
TRUNCATE TABLE nom_table ;
```

In [2]:
import os
from dotenv import load_dotenv
# Ajouter aux variables environnementales celles contenues dans le .env
load_dotenv("../../../.env")

USER = os.environ.get("POSTGRESQL_LOCAL_USER")
PASSWORD = os.environ.get("POSTGRESQL_LOCAL_PASSWORD")

import psycopg2

# Connexion à la base de données
conn = psycopg2.connect(user=USER, password=PASSWORD, host="localhost", port="5432")
cur = conn.cursor()

# Créer une table
cur.execute("CREATE TABLE test (id SERIAL PRIMARY KEY, name VARCHAR(100));")

# Ajouter une colonne
cur.execute("ALTER TABLE test ADD COLUMN age INT;")

# Renommer une colonne
cur.execute("ALTER TABLE test RENAME COLUMN age TO user_age;")

# Changer le type de données d'une colonne
cur.execute("ALTER TABLE test ALTER COLUMN user_age TYPE DECIMAL;")

# Supprimer une colonne
cur.execute("ALTER TABLE test DROP COLUMN user_age;")

# Renommer la table
cur.execute("ALTER TABLE test RENAME TO new_test;")

# Supprimer la table
cur.execute("DROP TABLE new_test;")

# Fermer la connexion
cur.close()
conn.close()

In [ ]:
# import pandas as pd