# 1 & 2

In [16]:
import os
from dotenv import load_dotenv
# Ajouter aux variables environnementales celles contenues dans le .env
load_dotenv("../../../.env")

USER = os.environ.get("POSTGRESQL_LOCAL_USER")
PASSWORD = os.environ.get("POSTGRESQL_LOCAL_PASSWORD")

import psycopg2

try:
    # Connexion à PostgreSQL
    conn = psycopg2.connect(user=USER, password=PASSWORD, host="localhost", port="5432")
    conn.autocommit = True
    cur = conn.cursor()

    try:
    # Création de la base de données test_db
        cur.execute("CREATE DATABASE  test_db;")
        print("Base de données 'test_db' créée avec succès.")

    except  Exception as e:
        if "already exists" in str(e):
            print(f"Database test_db already exists")
        else:
            raise

    # Connexion à la base de données test_db
    conn.close()
    conn = psycopg2.connect(dbname="test_db", user=USER, password=PASSWORD, host="localhost", port="5432")
    cur = conn.cursor()

    # Création d'une table 'items'
    cur.execute("DROP TABLE IF EXISTS items;")
    cur.execute("""
        CREATE TABLE items (
            item_id SERIAL PRIMARY KEY,
            item_name VARCHAR(255) NOT NULL,
            price DECIMAL NOT NULL,
            in_stock INT NOT NULL
        );
    """)
    print("Table 'items' créée avec succès.")

    # Insertion de données
    cur.execute("INSERT INTO items (item_name, price, in_stock) VALUES ('Pomme', 0.50, 50);")
    cur.execute("INSERT INTO items (item_name, price, in_stock) VALUES ('Banane', 0.30, 75);")
    cur.execute("INSERT INTO items (item_name, price, in_stock) VALUES ('Orange', 0.40, 100);")
    print("Données insérées avec succès.")

    # Mise à jour du prix de 'Pomme'
    cur.execute("UPDATE items SET price = 0.55 WHERE item_name = 'Pomme';")
    print("Prix de 'Pomme' mis à jour.")

    # Suppression de 'Banane'
    cur.execute("DELETE FROM items WHERE item_name = 'Banane';")
    print("'Banane' supprimée de la table.")

    # Renommage de la table 'items' en 'products'
    cur.execute("ALTER TABLE items RENAME TO products;")
    print("Table 'items' renommée en 'products'.")

    # Fermeture de la connexion
    cur.close()
    conn.close()

except psycopg2.Error as e:
    print(f"Erreur de connexion à la base de données PostgreSQL : {e}")

Database test_db already exists
Table 'items' créée avec succès.
Données insérées avec succès.
Prix de 'Pomme' mis à jour.
'Banane' supprimée de la table.
Table 'items' renommée en 'products'.

# 3 & 4

In [2]:
import psycopg2

try:
    # Connexion à PostgreSQL
    conn = psycopg2.connect(user="selim", password="", host="localhost", port="5432")
    conn.autocommit = True
    cur = conn.cursor()

    # Création de la base de données store_db
    cur.execute("CREATE DATABASE store_db;")
    print("Base de données 'store_db' créée.")

    # Connexion à store_db
    conn.close()
    conn = psycopg2.connect(dbname="store_db", user="selim", password="", host="localhost", port="5432")
    cur = conn.cursor()

    # Création de la table products
    cur.execute("""
        CREATE TABLE products (
            name VARCHAR(255) NOT NULL,
            price DECIMAL NOT NULL,
            quantity INT NOT NULL
        );
    """)
    print("Table 'products' créée.")

    # Insertion de données
    products = [('Pomme', 0.50, 50), ('Banane', 0.30, 75), ('Orange', 0.40, 100)]
    cur.executemany("INSERT INTO products (name, price, quantity) VALUES (%s, %s, %s);", products)
    print("Produits insérés.")

    # Mise à jour des prix
    cur.execute("UPDATE products SET price = 0.55 WHERE name = 'Pomme';")
    print("Prix de 'Pomme' mis à jour.")

    # Suppression d'un produit
    cur.execute("DELETE FROM products WHERE name = 'Banane';")
    print("'Banane' supprimée.")

    # Ajout d'une colonne category
    cur.execute("ALTER TABLE products ADD COLUMN category VARCHAR(255);")
    print("Colonne 'category' ajoutée.")

    # Utilisation de subqueries
    cur.execute("""
        SELECT name, price FROM products 
        WHERE price > (SELECT AVG(price) FROM products) 
        AND category = 'Fruit';
    """)
    high_priced_fruits = cur.fetchall()
    print("Fruits avec un prix supérieur à la moyenne :", high_priced_fruits)

    # Fermeture de la connexion
    cur.close()
    conn.close()

except psycopg2.Error as e:
    print(f"Erreur de connexion à la base de données PostgreSQL : {e}")

Base de données 'store_db' créée.
Table 'products' créée.
Produits insérés.
Prix de 'Pomme' mis à jour.
'Banane' supprimée.
Colonne 'category' ajoutée.
Fruits avec un prix supérieur à la moyenne : []